"""initial schema: families, users, assets (with auto-valuation fields), goals, snapshots, statement imports, transactions, processed emails

Revision ID: 095965015c8a
Revises: 
Create Date: 2026-07-18 12:40:14.327777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '095965015c8a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('families',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('target_amount', sa.Float(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('monthly_contribution', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('networth_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=True),
    sa.Column('total_assets', sa.Float(), nullable=True),
    sa.Column('total_liabilities', sa.Float(), nullable=True),
    sa.Column('net_worth', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processed_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.String(length=255), nullable=False),
    sa.Column('sender', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('result', sa.String(length=500), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('family_id', 'message_id', name='uq_family_message')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('relationship_label', sa.String(length=60), nullable=True),
    sa.Column('is_managed_profile', sa.Boolean(), nullable=True),
    sa.Column('is_active_member', sa.Boolean(), nullable=True),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('institution', sa.String(length=160), nullable=True),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('purchase_value', sa.Float(), nullable=True),
    sa.Column('principal_or_sum_assured', sa.Float(), nullable=True),
    sa.Column('interest_rate', sa.Float(), nullable=True),
    sa.Column('account_number_last4', sa.String(length=10), nullable=True),
    sa.Column('opened_on', sa.Date(), nullable=True),
    sa.Column('maturity_date', sa.Date(), nullable=True),
    sa.Column('units', sa.Float(), nullable=True),
    sa.Column('avg_buy_price', sa.Float(), nullable=True),
    sa.Column('scheme_code', sa.String(length=20), nullable=True),
    sa.Column('isin', sa.String(length=20), nullable=True),
    sa.Column('folio_number', sa.String(length=40), nullable=True),
    sa.Column('ticker', sa.String(length=20), nullable=True),
    sa.Column('last_valued_at', sa.DateTime(), nullable=True),
    sa.Column('nps_equity_pct', sa.Float(), nullable=True),
    sa.Column('nps_corp_debt_pct', sa.Float(), nullable=True),
    sa.Column('nps_gov_sec_pct', sa.Float(), nullable=True),
    sa.Column('nps_alt_pct', sa.Float(), nullable=True),
    sa.Column('emi_amount', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('statement_imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
    sa.Column('bank', sa.String(length=40), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('stored_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('accounts_found', sa.Integer(), nullable=True),
    sa.Column('transactions_found', sa.Integer(), nullable=True),
    sa.Column('warnings', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goal_assets',
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.PrimaryKeyConstraint('goal_id', 'asset_id')
    )
    op.create_table('imported_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('statement_import_id', sa.Integer(), nullable=False),
    sa.Column('account_kind', sa.String(length=10), nullable=True),
    sa.Column('account_number', sa.String(length=30), nullable=True),
    sa.Column('account_number_last4', sa.String(length=10), nullable=True),
    sa.Column('account_type', sa.String(length=120), nullable=True),
    sa.Column('opening_balance', sa.Float(), nullable=True),
    sa.Column('closing_balance', sa.Float(), nullable=True),
    sa.Column('debit_total', sa.Float(), nullable=True),
    sa.Column('credit_total', sa.Float(), nullable=True),
    sa.Column('interest_rate', sa.Float(), nullable=True),
    sa.Column('maturity_date', sa.Date(), nullable=True),
    sa.Column('matched_asset_id', sa.Integer(), nullable=True),
    sa.Column('suggested_name', sa.String(length=160), nullable=True),
    sa.ForeignKeyConstraint(['matched_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['statement_import_id'], ['statement_imports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('txn_date', sa.Date(), nullable=False),
    sa.Column('narration', sa.String(length=500), nullable=True),
    sa.Column('withdrawal', sa.Float(), nullable=True),
    sa.Column('deposit', sa.Float(), nullable=True),
    sa.Column('balance_after', sa.Float(), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('source_import_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['source_import_id'], ['statement_imports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imported_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imported_account_id', sa.Integer(), nullable=False),
    sa.Column('txn_date', sa.Date(), nullable=False),
    sa.Column('narration', sa.String(length=500), nullable=True),
    sa.Column('withdrawal', sa.Float(), nullable=True),
    sa.Column('deposit', sa.Float(), nullable=True),
    sa.Column('balance_after', sa.Float(), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('is_duplicate', sa.Boolean(), nullable=True),
    sa.Column('include', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['imported_account_id'], ['imported_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imported_transactions')
    op.drop_table('transactions')
    op.drop_table('imported_accounts')
    op.drop_table('goal_assets')
    op.drop_table('statement_imports')
    op.drop_table('assets')
    op.drop_table('users')
    op.drop_table('processed_emails')
    op.drop_table('networth_snapshots')
    op.drop_table('goals')
    op.drop_table('families')
    # ### end Alembic commands ###
