"""import source + email date, scan senders (Import Settings)

Revision ID: 3b123206d5e9
Revises: af8db5e7a090
Create Date: 2026-07-20 00:22:33.546359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b123206d5e9'
down_revision = 'af8db5e7a090'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_senders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('attachment_password', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('statement_imports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('email_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('statement_imports', schema=None) as batch_op:
        batch_op.drop_column('email_date')
        batch_op.drop_column('source')

    op.drop_table('scan_senders')
    # ### end Alembic commands ###
