"""duplicate guard (file_hash) + asset cashflows for XIRR

Revision ID: af8db5e7a090
Revises: 095965015c8a
Create Date: 2026-07-19 15:00:00.859720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af8db5e7a090'
down_revision = '095965015c8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_cashflows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('flow_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('units', sa.Float(), nullable=True),
    sa.Column('nav', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('synthetic', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'flow_date', 'amount', 'units', name='uq_asset_flow')
    )
    with op.batch_alter_table('statement_imports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_hash', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_statement_imports_file_hash'), ['file_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('statement_imports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_statement_imports_file_hash'))
        batch_op.drop_column('file_hash')

    op.drop_table('asset_cashflows')
    # ### end Alembic commands ###
