"""statement_imports.asset_owner_id — import on behalf of a family member

Revision ID: c1a4f9e6b2d3
Revises: 3b123206d5e9
Create Date: 2026-07-23 16:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1a4f9e6b2d3'
down_revision = '3b123206d5e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('statement_imports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asset_owner_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_statement_imports_asset_owner_id', 'users', ['asset_owner_id'], ['id']
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('statement_imports', schema=None) as batch_op:
        batch_op.drop_constraint('fk_statement_imports_asset_owner_id', type_='foreignkey')
        batch_op.drop_column('asset_owner_id')
    # ### end Alembic commands ###
