"""statement_imports.supersedes_import_id — reupload/override/diff

Revision ID: d2e5a8f4c1b7
Revises: c1a4f9e6b2d3
Create Date: 2026-07-23 18:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2e5a8f4c1b7'
down_revision = 'c1a4f9e6b2d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('statement_imports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supersedes_import_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_statement_imports_supersedes_import_id', 'statement_imports',
            ['supersedes_import_id'], ['id']
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('statement_imports', schema=None) as batch_op:
        batch_op.drop_constraint('fk_statement_imports_supersedes_import_id', type_='foreignkey')
        batch_op.drop_column('supersedes_import_id')
    # ### end Alembic commands ###
